#Definitions of the devices used in the experiment (except pumps and hotplate, which are defined in the fluidic_design_autopoly.json file))

peristaltic_pumps:
- name: Solvent_Peri_Pump
  com_port: COM15
  address: 1

- name: Polymer_Peri_Pump 
  com_port: COM12
  address: 2   


linear_actuator:
    com_port: COM12


solenoid_valve_precipitation:
    com_port: COM12


solenoid_valve_gas:
    com_port: COM12


#NMR:

#UV_VIS:    