peristaltic_pumps:
  - name: solvent_peri_pump
    com_port: COM10
    address: 1
  - name: polymer_peri_pump 
    com_port: COM12
    address: 2

syringe_pumps:
  - name: annalytics_syringe_pump # pump for the pumping of things to NMR and UV/Vis cells
    com_port: COM3
    address: 1
    syringe_volume: 0.01
  - name: monomer_solvent_syringe_pump # pump for the pumping of monomer and solvent to the reactor 
    com_port: COM4
    address: 2
    syringe_volume: 0.01
  - name: initiator_CTA_syringe_pump # pump for the pumping of initiator and CTA to the reactor
    com_port: COM5
    address: 3
    syringe_volume: 0.01
  - name: precipitation_syringe_pump # pump for the pumping of the methanol and polymer to the precipitation cell
    com_port: COM6
    address: 4
    syringe_volume: 0.01

hotplate:
    com_port: COM7    


linear_actuator:
    com_port: COM8

solenoid_valve:
    com_port: COM9